<?php
/**
 * Created by PhpStorm.
 * users: ahmadbiz
 * Date: 2017-11-05
 * Time: 3:31 PM
 */

class Customer extends Account{


    public function __set($name, $value)
    {
        parent::__set($name, $value); // TODO: Change the autogenerated stub
    }

    public function __get($name)
    {
        return parent::__get($name); // TODO: Change the autogenerated stub
    }

}