-- MySQL Script generated by MySQL Workbench
-- Tue Oct 24 08:55:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema compstor_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema compstor_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compstor_db` DEFAULT CHARACTER SET utf8 ;
USE `compstor_db` ;

-- -----------------------------------------------------
-- Table `compstor_db`.`Account_tbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Account_tbl` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Email` VARCHAR(100) NOT NULL,
  `PhoneNumber` VARCHAR(15) NULL,
  `Admin` TINYINT(1) NULL,
  `password` VARCHAR(45) NULL,
  `StreetName` VARCHAR(45) NULL,
  `StreetNumber` INT(11) NULL,
  `City` VARCHAR(45) NULL,
  `Province` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `PostalCode` VARCHAR(45) NULL,
  `isActive` TINYINT(1) NULL,
  PRIMARY KEY (`ID`, `Email`),
  INDEX `Account_idx` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Purchases` (
  `PurchaseID` INT(11) NOT NULL,
  `PurchaseDate` DATETIME NULL,
  `AccountID` INT(11) NOT NULL,
  `TotalCost` DOUBLE NULL,
  PRIMARY KEY (`PurchaseID`, `AccountID`),
  INDEX `AccountIDPurchases_idx` (`AccountID` ASC),
  INDEX `PurchaseID` (`PurchaseID` ASC),
  CONSTRAINT `AccountIDPurchases`
    FOREIGN KEY (`AccountID`)
    REFERENCES `compstor_db`.`Account_tbl` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Tablet_tbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Tablet_tbl` (
  `ID` INT(11) NOT NULL,
  `Key` VARCHAR(10) NULL,
  `Value` VARCHAR(10) NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `SerialNumber`),
  INDEX `SerialNumber` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Laptop_tbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Laptop_tbl` (
  `ID` INT(11) NOT NULL,
  `Key` VARCHAR(10) NULL,
  `Value` VARCHAR(10) NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `SerialNumber`),
  INDEX `SerialNumber` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Monitor_tbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Monitor_tbl` (
  `ID` INT(11) NOT NULL,
  `Key` VARCHAR(10) NULL,
  `Value` VARCHAR(10) NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `SerialNumber`),
  INDEX `SerialNumber` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`DesktopComputer_tbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`DesktopComputer_tbl` (
  `ID` INT(11) NOT NULL,
  `Key` VARCHAR(10) NULL,
  `Value` VARCHAR(10) NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `SerialNumber`),
  INDEX `SerailNumber` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Purchaselist_tbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Purchaselist_tbl` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ProductSerialNumber` VARCHAR(45) NOT NULL,
  `PurchaseID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `ProductSerialNumber`, `PurchaseID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  UNIQUE INDEX `ProductSerialNumber_UNIQUE` (`ProductSerialNumber` ASC),
  INDEX `PurchaseID_idx` (`PurchaseID` ASC),
  INDEX `ProductSerialNumber_idx` (`ProductSerialNumber` ASC),
  CONSTRAINT `PurchaseID`
    FOREIGN KEY (`PurchaseID`)
    REFERENCES `compstor_db`.`Purchases` (`PurchaseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SerialMonitor`
    FOREIGN KEY (`ProductSerialNumber`)
    REFERENCES `compstor_db`.`Monitor_tbl` (`SerialNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SerialLaptop`
    FOREIGN KEY (`ProductSerialNumber`)
    REFERENCES `compstor_db`.`Laptop_tbl` (`SerialNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SerialTablet`
    FOREIGN KEY (`ProductSerialNumber`)
    REFERENCES `compstor_db`.`Tablet_tbl` (`SerialNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SerialComputer`
    FOREIGN KEY (`ProductSerialNumber`)
    REFERENCES `compstor_db`.`DesktopComputer_tbl` (`SerialNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Audit_tbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Audit_tbl` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `AccountID` INT(11) NOT NULL,
  `Logout` DATETIME NULL,
  `Login` DATETIME NULL,
  PRIMARY KEY (`ID`, `AccountID`),
  INDEX `AccountID_idx` (`AccountID` ASC),
  CONSTRAINT `AccountIDAudit`
    FOREIGN KEY (`AccountID`)
    REFERENCES `compstor_db`.`Account_tbl` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Product_tbl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Product_tbl` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
