-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 18:44:19 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema compstor_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema compstor_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compstor_db` DEFAULT CHARACTER SET utf8 ;
USE `compstor_db` ;

-- -----------------------------------------------------
-- Table `compstor_db`.`DesktopComputer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`DesktopComputer` (
  `ComputerModelNumber` VARCHAR(45) NOT NULL,
  `ComputerDimensions` VARCHAR(10) NOT NULL,
  `ComputerBrand` VARCHAR(45) NOT NULL,
  `ComputerPrice` DECIMAL(2) NOT NULL,
  `ComputerCPUType` VARCHAR(45) NOT NULL,
  `ComputerCoreNumber` INT NOT NULL,
  `ComputerRAMSize` INT NOT NULL,
  `ComputerWeight` DECIMAL(2) NOT NULL,
  `ComputerHDDSize` INT NOT NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ComputerModelNumber`, `SerialNumber`),
  UNIQUE INDEX `ComputerModelNumber_UNIQUE` (`ComputerModelNumber` ASC),
  INDEX `SerialNumber_idx` (`SerialNumber` ASC),
  UNIQUE INDEX `SerialNumber_UNIQUE` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Monitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Monitor` (
  `MonitorModelNumber` VARCHAR(45) NOT NULL,
  `MonitorSize` DECIMAL(2) NOT NULL,
  `MonitorBrand` VARCHAR(45) NOT NULL,
  `MonitorPrice` DECIMAL(2) NOT NULL,
  `MonitorWeight` DECIMAL(2) NOT NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MonitorModelNumber`, `SerialNumber`),
  UNIQUE INDEX `MonitorModelNumber_UNIQUE` (`MonitorModelNumber` ASC),
  INDEX `SerialNumber_idx` (`SerialNumber` ASC),
  UNIQUE INDEX `SerialNumber_UNIQUE` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Laptop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Laptop` (
  `ComputerModelNumber` VARCHAR(45) NOT NULL,
  `ComputerDisplayDimensions` DECIMAL(2) NOT NULL,
  `ComputerBrand` VARCHAR(45) NOT NULL,
  `ComputerPrice` DECIMAL(2) NOT NULL,
  `ComputerCPUType` VARCHAR(45) NOT NULL,
  `ComputerCoreNumber` INT NOT NULL,
  `ComputerRAMSize` INT NOT NULL,
  `ComputerWeight` DECIMAL(2) NOT NULL,
  `ComputerHDDSize` INT NOT NULL,
  `ComputerBattery` VARCHAR(45) NOT NULL,
  `ComputerOS` VARCHAR(45) NOT NULL,
  `ComputerToucheScreenToggle` TINYINT(1) NULL,
  `ComputerCameraToggle` TINYINT(1) NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ComputerModelNumber`, `SerialNumber`),
  UNIQUE INDEX `ComputerModelNumber_UNIQUE` (`ComputerModelNumber` ASC),
  INDEX `SerialNumber_idx` (`SerialNumber` ASC),
  UNIQUE INDEX `SerialNumber_UNIQUE` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Tablet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Tablet` (
  `ComputerModelNumber` VARCHAR(45) NOT NULL,
  `ComputerDisplaySize` INT NOT NULL,
  `ComputerDisplayDimesions` DECIMAL(2) NOT NULL,
  `ComputerBrand` VARCHAR(45) NOT NULL,
  `ComputerPrice` DECIMAL(2) NOT NULL,
  `ComputerCPUType` VARCHAR(45) NOT NULL,
  `ComputerCoreNumber` INT NOT NULL,
  `ComputerRAMSize` INT NOT NULL,
  `ComputerWeight` DECIMAL(2) NOT NULL,
  `ComputerHDDSize` INT NOT NULL,
  `ComputerBattery` VARCHAR(45) NOT NULL,
  `ComputerOS` VARCHAR(45) NOT NULL,
  `ComputerCameraInformation` VARCHAR(45) NOT NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ComputerModelNumber`, `SerialNumber`),
  UNIQUE INDEX `ComputerModelNumber_UNIQUE` (`ComputerModelNumber` ASC),
  UNIQUE INDEX `SerialNumber_UNIQUE` (`SerialNumber` ASC),
  INDEX `SerialNumber_idx` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Account` (
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Email` VARCHAR(100) NOT NULL,
  `PhoneNumber` VARCHAR(15) NULL,
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `StreetName` VARCHAR(45) NULL,
  `StreetNumber` INT NULL,
  `Province` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `PostalCode` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Type` VARCHAR(1) NOT NULL DEFAULT 'C',
  PRIMARY KEY (`Email`, `UserID`),
  INDEX `UserID_idx` (`UserID` ASC),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Transaction` (
  `ID` INT NOT NULL DEFAULT 0,
  `AccountID` INT NOT NULL,
  `TransactionID` VARCHAR(45) NOT NULL,
  `TotalCost` DOUBLE NULL,
  `TransactionDate` DATE NULL,
  `TransactionTime` TIME NULL,
  `TransactionType` VARCHAR(1) NULL,
  PRIMARY KEY (`ID`, `TransactionID`, `AccountID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `AcountID_idx` (`AccountID` ASC),
  INDEX `PurchaseID_idx` (`TransactionID` ASC),
  UNIQUE INDEX `PurchaseID_UNIQUE` (`TransactionID` ASC),
  UNIQUE INDEX `AccountID_UNIQUE` (`AccountID` ASC),
  INDEX `ID_idx` (`ID` ASC),
  CONSTRAINT `UserID`
    FOREIGN KEY (`AccountID`)
    REFERENCES `compstor_db`.`Account` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`TransactionList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`TransactionList` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TransactionID` VARCHAR(45) NOT NULL,
  `ProductSerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `TransactionID`, `ProductSerialNumber`),
  UNIQUE INDEX `PurchaseID_UNIQUE` (`TransactionID` ASC),
  UNIQUE INDEX `ProductSerialNumber_UNIQUE` (`ProductSerialNumber` ASC),
  INDEX `PurchaseID_idx` (`TransactionID` ASC),
  INDEX `ProductSerialNumber_idx` (`ProductSerialNumber` ASC),
  CONSTRAINT `PurchaseTablet`
    FOREIGN KEY (`ProductSerialNumber`)
    REFERENCES `compstor_db`.`Tablet` (`SerialNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PurchaseDesktop`
    FOREIGN KEY (`ProductSerialNumber`)
    REFERENCES `compstor_db`.`DesktopComputer` (`SerialNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PurchaseLaptop`
    FOREIGN KEY (`ProductSerialNumber`)
    REFERENCES `compstor_db`.`Laptop` (`SerialNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PurchaseMonitor`
    FOREIGN KEY (`ProductSerialNumber`)
    REFERENCES `compstor_db`.`Monitor` (`SerialNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PurchassID`
    FOREIGN KEY (`TransactionID`)
    REFERENCES `compstor_db`.`Transaction` (`TransactionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Audit` (
  `AccountID` INT NOT NULL,
  `IsActive` TINYINT(1) NULL,
  `Login` DATE NULL,
  `Logout` DATE NULL,
  PRIMARY KEY (`AccountID`),
  INDEX `AccountID_idx` (`AccountID` ASC),
  UNIQUE INDEX `AccountID_UNIQUE` (`AccountID` ASC),
  CONSTRAINT `AccountID`
    FOREIGN KEY (`AccountID`)
    REFERENCES `compstor_db`.`Account` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Product` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
