-- MySQL Script generated by MySQL Workbench
-- Thu Nov 23 00:58:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema compstor_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema compstor_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compstor_db` DEFAULT CHARACTER SET utf8 ;
USE `compstor_db` ;

-- -----------------------------------------------------
-- Table `compstor_db`.`DesktopComputer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`DesktopComputer` (
  `ModelNumber` VARCHAR(45) NOT NULL,
  `Dimensions` VARCHAR(10) NOT NULL,
  `Brand` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(6,2) NOT NULL,
  `CPUType` VARCHAR(45) NOT NULL,
  `CoreNumber` INT NOT NULL,
  `RAMSize` INT NOT NULL,
  `Weight` DECIMAL(4,2) NOT NULL,
  `HDDSize` INT NOT NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ModelNumber`, `SerialNumber`),
  INDEX `SerialNumber_idx` (`SerialNumber` ASC),
  UNIQUE INDEX `SerialNumber_UNIQUE` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Monitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Monitor` (
  `ModelNumber` VARCHAR(45) NOT NULL,
  `DisplayDimensions` INT NOT NULL,
  `Brand` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(6,2) NOT NULL,
  `Weight` DECIMAL(4,2) NOT NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ModelNumber`, `SerialNumber`),
  INDEX `SerialNumber_idx` (`SerialNumber` ASC),
  UNIQUE INDEX `SerialNumber_UNIQUE` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Laptop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Laptop` (
  `ModelNumber` VARCHAR(45) NOT NULL,
  `DisplayDimensions` VARCHAR(10) NOT NULL,
  `Brand` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(6,2) NOT NULL,
  `CPUType` VARCHAR(45) NOT NULL,
  `CoreNumber` INT NOT NULL,
  `RAMSize` INT NOT NULL,
  `Weight` DECIMAL(4,2) NOT NULL,
  `HDDSize` INT NOT NULL,
  `Battery` VARCHAR(45) NOT NULL,
  `OS` VARCHAR(45) NOT NULL,
  `ToucheScreenToggle` TINYINT(1) NULL,
  `CameraToggle` TINYINT(1) NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ModelNumber`, `SerialNumber`),
  INDEX `SerialNumber_idx` (`SerialNumber` ASC),
  UNIQUE INDEX `SerialNumber_UNIQUE` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Tablet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Tablet` (
  `ModelNumber` VARCHAR(45) NOT NULL,
  `DisplaySize` INT NOT NULL,
  `DisplayDimensions` VARCHAR(10) NOT NULL,
  `Brand` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(6,2) NOT NULL,
  `CPUType` VARCHAR(45) NOT NULL,
  `CoreNumber` INT NOT NULL,
  `RAMSize` INT NOT NULL,
  `Weight` DECIMAL(4,2) NOT NULL,
  `HDDSize` INT NOT NULL,
  `Battery` VARCHAR(45) NOT NULL,
  `OS` VARCHAR(45) NOT NULL,
  `CameraInformation` VARCHAR(45) NOT NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ModelNumber`, `SerialNumber`),
  UNIQUE INDEX `SerialNumber_UNIQUE` (`SerialNumber` ASC),
  INDEX `SerialNumber_idx` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Account` (
  `UserID` INT NOT NULL DEFAULT 1,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Email` VARCHAR(100) NOT NULL,
  `PhoneNumber` VARCHAR(15) NULL,
  `StreetName` VARCHAR(45) NULL,
  `StreetNumber` VARCHAR(10) NULL,
  `Province` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `PostalCode` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Type` VARCHAR(1) NOT NULL DEFAULT 'C',
  PRIMARY KEY (`UserID`, `Email`),
  INDEX `UserID_idx` (`UserID` ASC),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Transaction` (
  `AccountID` INT NOT NULL,
  `TransactionID` VARCHAR(45) NOT NULL,
  `TotalCost` DOUBLE NULL,
  `TransactionDate` DATE NULL,
  `TransactionTime` TIME NULL,
  `TransactionType` VARCHAR(1) NULL,
  PRIMARY KEY (`TransactionID`, `AccountID`),
  INDEX `AcountID_idx` (`AccountID` ASC),
  INDEX `PurchaseID_idx` (`TransactionID` ASC),
  UNIQUE INDEX `PurchaseID_UNIQUE` (`TransactionID` ASC),
  CONSTRAINT `UserID`
    FOREIGN KEY (`AccountID`)
    REFERENCES `compstor_db`.`Account` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`TransactionList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`TransactionList` (
  `TransactionID` VARCHAR(45) NOT NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TransactionID`, `SerialNumber`),
  INDEX `PurchaseID_idx` (`TransactionID` ASC),
  INDEX `ProductSerialNumber_idx` (`SerialNumber` ASC),
  UNIQUE INDEX `ProductSerialNumber_UNIQUE` (`SerialNumber` ASC),
  CONSTRAINT `PurchassID`
    FOREIGN KEY (`TransactionID`)
    REFERENCES `compstor_db`.`Transaction` (`TransactionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Audit` (
  `AccountID` INT NOT NULL,
  `IsActive` TINYINT(1) NULL,
  `Login` DATE NULL,
  `Logout` DATE NULL,
  PRIMARY KEY (`AccountID`),
  INDEX `AccountID_idx` (`AccountID` ASC),
  UNIQUE INDEX `AccountID_UNIQUE` (`AccountID` ASC),
  CONSTRAINT `AccountID`
    FOREIGN KEY (`AccountID`)
    REFERENCES `compstor_db`.`Account` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstor_db`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstor_db`.`Product` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
