-- MySQL Script generated by MySQL Workbench
-- Wed Nov  1 01:40:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema compstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema compstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compstore` DEFAULT CHARACTER SET utf8 ;
USE `compstore` ;

-- -----------------------------------------------------
-- Table `compstore`.`DesktopComputer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstore`.`DesktopComputer` (
  `ComputerModelNumber` VARCHAR(45) NOT NULL,
  `ComputerDimensions` VARCHAR(10) NOT NULL,
  `ComputerBrand` VARCHAR(45) NOT NULL,
  `ComputerPrice` DECIMAL(2) NOT NULL,
  `ComputerCPUType` VARCHAR(45) NOT NULL,
  `ComputerCoreNumber` INT NOT NULL,
  `ComputerRAMSize` INT NOT NULL,
  `ComputerWeight` DECIMAL(2) NOT NULL,
  `ComputerHDDSize` INT NOT NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ComputerModelNumber`, `SerialNumber`),
  UNIQUE INDEX `ComputerModelNumber_UNIQUE` (`ComputerModelNumber` ASC),
  INDEX `SerialNumber_idx` (`SerialNumber` ASC),
  UNIQUE INDEX `SerialNumber_UNIQUE` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstore`.`Monitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstore`.`Monitor` (
  `MonitorModelNumber` VARCHAR(45) NOT NULL,
  `MonitorSize` DECIMAL(2) NOT NULL,
  `MonitorBrand` VARCHAR(45) NOT NULL,
  `MonitorPrice` DECIMAL(2) NOT NULL,
  `MonitorWeight` DECIMAL(2) NOT NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MonitorModelNumber`, `SerialNumber`),
  UNIQUE INDEX `MonitorModelNumber_UNIQUE` (`MonitorModelNumber` ASC),
  INDEX `SerialNumber_idx` (`SerialNumber` ASC),
  UNIQUE INDEX `SerialNumber_UNIQUE` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstore`.`Laptop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstore`.`Laptop` (
  `ComputerModelNumber` VARCHAR(45) NOT NULL,
  `ComputerDisplayDimensions` DECIMAL(2) NOT NULL,
  `ComputerBrand` VARCHAR(45) NOT NULL,
  `ComputerPrice` DECIMAL(2) NOT NULL,
  `ComputerCPUType` VARCHAR(45) NOT NULL,
  `ComputerCoreNumber` INT NOT NULL,
  `ComputerRAMSize` INT NOT NULL,
  `ComputerWeight` DECIMAL(2) NOT NULL,
  `ComputerHDDSize` INT NOT NULL,
  `ComputerBattery` VARCHAR(45) NOT NULL,
  `ComputerOS` VARCHAR(45) NOT NULL,
  `ComputerToucheScreenToggle` TINYINT(1) NULL,
  `ComputerCameraToggle` TINYINT(1) NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ComputerModelNumber`, `SerialNumber`),
  UNIQUE INDEX `ComputerModelNumber_UNIQUE` (`ComputerModelNumber` ASC),
  INDEX `SerialNumber_idx` (`SerialNumber` ASC),
  UNIQUE INDEX `SerialNumber_UNIQUE` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstore`.`Tablet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstore`.`Tablet` (
  `ComputerModelNumber` VARCHAR(45) NOT NULL,
  `ComputerDisplaySize` INT NOT NULL,
  `ComputerDisplayDimesions` DECIMAL(2) NOT NULL,
  `ComputerBrand` VARCHAR(45) NOT NULL,
  `ComputerPrice` DECIMAL(2) NOT NULL,
  `ComputerCPUType` VARCHAR(45) NOT NULL,
  `ComputerCoreNumber` INT NOT NULL,
  `ComputerRAMSize` INT NOT NULL,
  `ComputerWeight` DECIMAL(2) NOT NULL,
  `ComputerHDDSize` INT NOT NULL,
  `ComputerBattery` VARCHAR(45) NOT NULL,
  `ComputerOS` VARCHAR(45) NOT NULL,
  `ComputerCameraInformation` VARCHAR(45) NOT NULL,
  `SerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ComputerModelNumber`, `SerialNumber`),
  UNIQUE INDEX `ComputerModelNumber_UNIQUE` (`ComputerModelNumber` ASC),
  UNIQUE INDEX `SerialNumber_UNIQUE` (`SerialNumber` ASC),
  INDEX `SerialNumber_idx` (`SerialNumber` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstore`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstore`.`Account` (
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `Email` VARCHAR(100) NOT NULL,
  `PhoneNumber` VARCHAR(15) NULL,
  `UserID` INT NOT NULL,
  `StreetName` VARCHAR(45) NULL,
  `StreetNumber` VARCHAR(45) NULL,
  `Province` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `PostalCode` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Admin` TINYINT(1) NULL,
  PRIMARY KEY (`Email`, `UserID`),
  INDEX `UserID_idx` (`UserID` ASC),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstore`.`Purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstore`.`Purchases` (
  `ID` INT NOT NULL,
  `AccountID` INT NOT NULL,
  `PurchaseID` VARCHAR(45) NOT NULL,
  `TotalCost` DOUBLE NULL,
  `PurchaseDate` DATETIME NULL,
  PRIMARY KEY (`ID`, `PurchaseID`, `AccountID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `AcountID_idx` (`AccountID` ASC),
  INDEX `PurchaseID_idx` (`PurchaseID` ASC),
  CONSTRAINT `UserID`
    FOREIGN KEY (`AccountID`)
    REFERENCES `compstore`.`Account` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstore`.`PurchaseList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstore`.`PurchaseList` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PurchaseID` VARCHAR(45) NOT NULL,
  `ProductSerialNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `PurchaseID`, `ProductSerialNumber`),
  UNIQUE INDEX `PurchaseID_UNIQUE` (`PurchaseID` ASC),
  UNIQUE INDEX `ProductSerialNumber_UNIQUE` (`ProductSerialNumber` ASC),
  INDEX `PurchaseID_idx` (`PurchaseID` ASC),
  INDEX `ProductSerialNumber_idx` (`ProductSerialNumber` ASC),
  CONSTRAINT `PurchaseTablet`
    FOREIGN KEY (`ProductSerialNumber`)
    REFERENCES `compstore`.`Tablet` (`SerialNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PurchaseDesktop`
    FOREIGN KEY (`ProductSerialNumber`)
    REFERENCES `compstore`.`DesktopComputer` (`SerialNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PurchaseLaptop`
    FOREIGN KEY (`ProductSerialNumber`)
    REFERENCES `compstore`.`Laptop` (`SerialNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PurchaseMonitor`
    FOREIGN KEY (`ProductSerialNumber`)
    REFERENCES `compstore`.`Monitor` (`SerialNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PurchassID`
    FOREIGN KEY (`PurchaseID`)
    REFERENCES `compstore`.`Purchases` (`PurchaseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstore`.`Audit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstore`.`Audit` (
  `AccountID` INT NOT NULL,
  `IsActive` TINYINT(1) NULL,
  `Login` DATE NULL,
  `Logout` DATE NULL,
  PRIMARY KEY (`AccountID`),
  INDEX `AccountID_idx` (`AccountID` ASC),
  UNIQUE INDEX `AccountID_UNIQUE` (`AccountID` ASC),
  CONSTRAINT `AccountID`
    FOREIGN KEY (`AccountID`)
    REFERENCES `compstore`.`Account` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compstore`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compstore`.`Product` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL,
  `Quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
